# Generated by Django 2.2.3 on 2020-07-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200716_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('express', 'Oloja Express')], default='express', max_length=13),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paystack', 'Paystack'), ('crypto', 'Crypto Pay'), ('pay_on_delivery', 'Cash on delivery')], default='flutterwave', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=50, null=True),
        ),
    ]
